### ISSUE TITLE
6.1.0 TypeScript definition error

### ISSUE THREAD

**Issue by twoeo** [dcodeIO/protobuf.js#552]
**Environment**
TypeScript 2.1.1
NodeJS 6.7.0

**Compile Error**
> node_modules/protobufjs/types/protobuf.js.d.ts(1185,10): error TS2417: Class static side 'typeof Root' incorrectly extends base class static side 'typeof Namespace'.
  Types of property 'fromJSON' are incompatible.
    Type '(json: any, root?: Root | undefined) => Root' is not assignable to type '(name: string, json: Object) => Namespace'.
      Types of parameters 'root' and 'json' are incompatible.
        Type 'Object' is not assignable to type 'Root | undefined'.
          The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
            Type 'Object' is not assignable to type 'Root'.
              The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
                Property 'deferred' is missing in type 'Object'.

**Comment by dcodeIO** [comment]
Sorry, I am not quite sure where this is coming from. Maybe try typescript `2.2.0-dev.20161212`.

**Comment by dcodeIO** [comment]
Does it work with 2.2.0-dev?

**Comment by endel** [comment]
The latest stable version is `2.1.4`, I'd recommend to test using it.

**Comment by dcodeIO** [comment]
Closing this for now. Feel free to reopen if the issue persists.
