### ISSUE TITLE
Parse error, Enum is not a function.

### ISSUE THREAD

**Issue by pvsong** [dcodeIO/protobuf.js#990]
Hi, 
I have a problem when parsing at version 6.8.5 but work fine with 6.7.0

protobuf.js version: <6.8.5>

```js
       const str  = `
        syntax = "proto3";
        package Proto_common;
        option optimize_for = SPEED;

        enum Error {
            ERR_GENERAL = 0;
            ERR_AUTHENTICATION = 1;
            ERR_ROOM_INVALID = 2;
            ERR_BALANCE_INVALID = 3;
            ERR_QR_CODE_INVALID = 4;
        }
       `;

       protobuf.parse(str).root
```

![simulator screen shot - iphone 6 - 2018-02-21 at 12 09 12](https://user-images.githubusercontent.com/9800579/36464061-362ad55a-1700-11e8-8846-0561faee98c8.png)

**Comment by SlyryD** [comment]
Same exact issue here for protobuf.js v6.8.6 on React Native.

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
