### ISSUE TITLE
Old code breaks on ProtoBuf.protoFromString(myProtoFileString, importedBuilder) 

### ISSUE THREAD

**Issue by tiantian20007** [dcodeIO/ProtoBuf.js#118]
After upgrade to 2.3.1, old code breaks on ProtoBuf.protoFromString(myProtoFileString, importedBuilder):

ProtoBuf.js:3340:Error: Cannot determine import root: File name is unknown

Yes I use "import" in proto, but I've already load proto file into myProtoFileString, and already got that imported builder, why should I need to give the third filename parameter?

Even if I give a filename as the third parameter for ProtoBuf.protoFromString, it will still break because ProtoBuf will use XmlHttpRequest to load that file, however, my javascript runtime dose not support XmlHttpRequest.
I think it's better to give user a chance to choose what method to use for file loading either.

**Comment by dcodeIO** [comment]
Closing this for now. Feel free to reopen it again if there are still some issues.

**Comment by gwalschl** [comment]
I am experiencing the same issue.  However, I have a "graph" of files based on import statements and those files have different protobuf "package" statements, effectively putting them in different namespaces.  Would combining those files work in this case?

**Comment by dcodeIO** [comment]
Different package statements shouldn't be a problem. It's all combined into a single namespace.
